# This is a basic workflow to help you get started with Actions

name: "GitHub Actions SMZDM Bot"

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    # branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 23 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      # Runs a set of commands using the runners shell
      - name: Install requirements
        run: |
          pip install -r requirements.txt

      - name: Working
        env:
          COOKIES: ${{ __jsluid_h=21315ad16455109e17fcf0f8352743c8; __ckguid=wyw5x7KoecjSHFte9HwTF4; r_sort_type=score; __jsluid_s=32f24f5b8405b2ef4ea2a5eb46a85375; device_id=210495475716251987526984442d0181b9550faf0d931a052328a308f0; userId=Lutherlee|8829349692; smzdm_user_source=32C9763CE05D88213828C3B835D6094C; _ga=GA1.2.531197695.1625141481; _ga_09SRZM2FDD=GS1.1.1627896423.1.1.1627896636.0; homepage_sug=b; footer_floating_layer=0; sess=AT-wYR85vGFz3zlF%2ByUHGsdfHAsUALlgrSFHvxpU2d8oFoO7NCfswZ2duXuURsr1lvWTRHVupi%2FcZ8if4xm1XnnMIGwirVVW%2B2dLxpNKYbsUp%2FQbQY62G7jmWNk; user=Lutherlee%7C8829349692; smzdm_id=8829349692; smzdm_user_view=8C284A486A8686B03CD4FB337FA9E34E; ss_ab=ss54; Hm_lvt_9b7ac3d38f30fe89ff0b8a0546904e58=1640310012,1640945240,1640945326,1641349451; _zdmA.vid=*; sensorsdata2015jssdkcross=%7B%22distinct_id%22%3A%228829349692%22%2C%22first_id%22%3A%2217a61fb0a9c359-0f829a3e7aee71-3355427b-4953600-17a61fb0a9f2d2%22%2C%22props%22%3A%7B%22%24latest_traffic_source_type%22%3A%22%E7%9B%B4%E6%8E%A5%E6%B5%81%E9%87%8F%22%2C%22%24latest_search_keyword%22%3A%22%E6%9C%AA%E5%8F%96%E5%88%B0%E5%80%BC_%E7%9B%B4%E6%8E%A5%E6%89%93%E5%BC%80%22%2C%22%24latest_referrer%22%3A%22%22%2C%22%24latest_landing_page%22%3A%22https%3A%2F%2Fwww.smzdm.com%2F%22%7D%2C%22%24device_id%22%3A%2217a61fb0a9c359-0f829a3e7aee71-3355427b-4953600-17a61fb0a9f2d2%22%7D; ad_date=5; ad_json_feed=%7B%7D; s_his=NAS%2C4T%20%E7%B4%AB%E7%9B%98%2C%E5%A8%81%E8%81%94%E9%80%9A%2C%E5%A8%81%E8%81%94%E9%80%9A543%2C%E5%A8%81%E8%81%94%E9%80%9A453%2CTP%20link%2C%E9%B8%A1%E8%9B%8B%2Casus%20%E5%8D%8E%E7%A1%95%20%E6%97%A0%E7%95%8F15%2C%E5%A4%9C%E5%8B%A4%E4%BA%BA%2C3080ti; _zdmA.uid=ZDMA.rYN_NZDyJ.1641350857.2419200; Hm_lpvt_9b7ac3d38f30fe89ff0b8a0546904e58=1641350857; bannerCounter=%5B%7B%22number%22%3A1%2C%22surplus%22%3A1%7D%2C%7B%22number%22%3A1%2C%22surplus%22%3A1%7D%2C%7B%22number%22%3A1%2C%22surplus%22%3A1%7D%2C%7B%22number%22%3A1%2C%22surplus%22%3A1%7D%2C%7B%22number%22%3A1%2C%22surplus%22%3A1%7D%2C%7B%22number%22%3A0%2C%22surplus%22%3A1%7D%5D; _zdmA.time=1641350911150.0.https%3A%2F%2Fwww.smzdm.com%2F }}
          SERVERCHAN_SECRETKEY: ${{ secrets.SERVERCHAN_SECRETKEY }}
        run: python main.py #>SMZDM_Bot.log
